using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;

namespace Fosa.AvatarTextureOptimizer.Editor
{
    /// <summary>
    /// Rewrites meshes so UVs point into the atlases. Only the affected UV channel changes —
    /// positions, normals, tangents (NEVER recomputed), skinning and blendshapes stay untouched.
    /// AAO compatibility: when AAO uses the channel, original UVs are evacuated to a free channel
    /// and registered via UVUsageCompabilityAPI. / 重写网格UV指向图集：仅改受影响的UV通道，
    /// 切线绝不重算；AAO 使用该通道时将原UV疏散至空闲通道并注册。
    /// </summary>
    internal class MeshRewriter
    {
        private readonly Dictionary<(UvGroup, UvIsland), PlacedIsland> _placements;
        private readonly Dictionary<Mesh, Mesh> _cloned = new Dictionary<Mesh, Mesh>();

        internal readonly List<string> Warnings = new List<string>();

        internal MeshRewriter(Dictionary<(UvGroup, UvIsland), PlacedIsland> placements)
        {
            _placements = placements;
        }

        /// <summary>Meshes generated by the rewriter (for asset saving). / 重写器生成的网格（供保存）。</summary>
        internal readonly List<Mesh> GeneratedMeshes = new List<Mesh>();

        /// <summary>
        /// Rewrite one group's mesh. Channels are applied cumulatively to the SAME clone so
        /// multi-channel UVs never lose each other's rewrites (cached per source mesh).
        /// / 重写该组网格：多通道改动累积到同一个克隆上，互不覆盖。
        /// </summary>
        internal Mesh Rewrite(UvGroup group)
        {
            var src = group.mesh;

            if (!_cloned.TryGetValue(src, out var mesh) || mesh == src)
            {
                mesh = Object.Instantiate(src);
                mesh.name = "ATO_" + src.name;
                GeneratedMeshes.Add(mesh);
            }

            if (!RewriteChannel(src, group, out var newUvs, out var reason))
            {
                Warnings.Add($"mesh '{src.name}' ch{group.channel} rewrite failed ({reason}); UVs untouched / 网格UV未改写");
                _cloned[src] = src; // stop using a partially rewritten clone / 弃用半成品克隆
                return src;
            }

            mesh.SetUVs(group.channel, newUvs);

            // ---- AAO UV evacuation / AAO UV疏散 ----
            var smr = group.primaryRenderer?.smr;
            if (smr != null && AAOCompat.IsTexCoordUsed(smr, group.channel))
            {
                int saved = FindFreeChannel(mesh);
                if (saved >= 0)
                {
                    var originals = new List<Vector2>();
                    src.GetUVs(group.channel, originals);
                    mesh.SetUVs(saved, originals);
                    if (AAOCompat.RegisterEvacuation(smr, group.channel, saved))
                        ATOLog.Info($"AAO UV evacuation '{mesh.name}': ch{group.channel} → ch{saved} / UV疏散完成");
                }
                else
                {
                    Warnings.Add($"no free UV channel to evacuate ch{group.channel} on '{mesh.name}' for AAO / 无空闲通道疏散");
                }
            }

            _cloned[src] = mesh;
            ATOLog.Info($"mesh rewritten: '{src.name}' ch{group.channel} → '{mesh.name}'");
            return mesh;
        }

        /// <summary>Compute the remapped UVs of a group's channel. / 计算该组通道重映射后的UV。</summary>
        private bool RewriteChannel(Mesh src, UvGroup group, out Vector2[] newUvs, out string reason)
        {
            reason = null;
            newUvs = null;

            var uvs = new List<Vector2>();
            src.GetUVs(group.channel, uvs);
            if (uvs.Count == 0) { reason = "no uvs"; return false; }

            // vertex → owning island (connected components make ownership unique)
            // 顶点→所属岛（连通分量保证归属唯一）
            var vertexIsland = new int[uvs.Count];
            for (int i = 0; i < vertexIsland.Length; i++) vertexIsland[i] = -1;
            var islandById = new Dictionary<int, UvIsland>();

            var masterOf = new Dictionary<int, UvIsland>();

            void Claim(UvIsland island, UvIsland master)
            {
                masterOf[island.id] = master;
                islandById.TryAdd(island.id, island);
                foreach (var vi in island.triangles)
                    if (vi >= 0 && vi < vertexIsland.Length && vertexIsland[vi] == -1)
                        vertexIsland[vi] = island.id;
            }

            foreach (var island in group.islands)
            {
                Claim(island, island);
                // merged duplicates share the master's atlas rect but keep their OWN uv offset
                // 合并副本共享主岛矩形，但保留自身 UV 偏移
                foreach (var m in island.mergedIslands) Claim(m, island);
            }

            var result = new Vector2[uvs.Count];
            var placementCache = new Dictionary<int, (UvIsland island, PlacedIsland placed)>();

            for (int v = 0; v < uvs.Count; v++)
            {
                var id = vertexIsland[v];
                if (id < 0)
                {
                    result[v] = uvs[v]; // vertex not used by any island / 未被使用的顶点保持原样
                    continue;
                }

                if (!placementCache.TryGetValue(id, out var entry))
                {
                    if (!islandById.TryGetValue(id, out var island))
                    {
                        reason = $"island {id} unknown / 未知岛";
                        return false;
                    }
                    var master = masterOf.TryGetValue(id, out var mo) ? mo : island;
                    if (!_placements.TryGetValue((group, master), out var placed))
                    {
                        reason = $"island {id} has no placement / 岛未装箱";
                        return false;
                    }
                    entry = (island, placed);
                    placementCache[id] = entry;
                }

                result[v] = MapUv(uvs[v], entry.island, entry.placed);
            }

            newUvs = result;
            return true;
        }

        /// <summary>Map an original UV into its atlas rect (half-texel inset + optional 90° rotation). / 原UV映射到图集矩形（半像素内缩+可选90°旋转）。</summary>
        internal static Vector2 MapUv(Vector2 uv, UvIsland island, PlacedIsland placed)
        {
            var b = island.uvBounds;
            float w = Mathf.Max(b.width, 1e-9f), h = Mathf.Max(b.height, 1e-9f);
            float u = Mathf.Clamp01((uv.x + island.uvOffset.x - b.x) / w);
            float v = Mathf.Clamp01((uv.y + island.uvOffset.y - b.y) / h);

            int iw = Mathf.Max(1, placed.IslandW);
            int ih = Mathf.Max(1, placed.IslandH);

            // half-texel inset keeps bilinear taps inside the island / 半像素内缩防止采样越岛
            float ui = (0.5f + u * (iw - 1)) / iw;
            float vi = (0.5f + v * (ih - 1)) / ih;

            float uu, vv, fw, fh;
            if (placed.Rotated90)
            {
                // clockwise rotation: footprint becomes ih × iw / 顺时针：占用变为 ih × iw
                uu = vi;
                vv = 1f - ui;
                fw = ih;
                fh = iw;
            }
            else
            {
                uu = ui;
                vv = vi;
                fw = iw;
                fh = ih;
            }

            float px = placed.X + 0.5f + uu * (fw - 1f);
            float py = placed.Y + 0.5f + vv * (fh - 1f);
            return new Vector2(px / placed.AtlasDims.x, py / placed.AtlasDims.y);
        }

        private static int FindFreeChannel(Mesh mesh)
        {
            for (int ch = 1; ch < 8; ch++)
            {
                if (!mesh.HasVertexAttribute(VertexAttribute.TexCoord0 + ch)) return ch;
            }
            return -1;
        }

        /// <summary>
        /// Merge two material slots of a mesh by combining their submeshes (used only when the
        /// final materials are identical &amp; opaque and no animation switches either slot).
        /// / 合并材质槽：仅在最终材质完全相同且为不透明、且动画不单独切换任一槽位时合并子网格。
        /// </summary>
        internal static Mesh MergeSlots(Mesh src, int keep, int remove)
        {
            var mesh = Object.Instantiate(src);
            mesh.name = src.name + "_ATO_SlotMerged" + keep;

            var keepIdx = src.GetIndices(keep, false);
            var removeIdx = src.GetIndices(remove, false);
            var merged = new int[keepIdx.Length + removeIdx.Length];
            keepIdx.CopyTo(merged, 0);
            removeIdx.CopyTo(merged, keepIdx.Length);

            int n = src.subMeshCount;
            mesh.subMeshCount = n - 1;
            for (int i = 0, j = 0; i < n; i++)
            {
                if (i == remove) continue;
                if (i == keep) mesh.SetIndices(merged, MeshTopology.Triangles, j, false);
                else mesh.SetIndices(src.GetIndices(i, false), MeshTopology.Triangles, j, false);
                j++;
            }

            return mesh;
        }
    }
}
