// ATO — Avatar Texture Optimizer
// Public extension points for advanced users and third-party developers.
// 面向高级用户与第三方开发者的公开扩展接口。
//
// Implement IATOPostProcessor in your own assembly; ATO discovers implementations via
// Unity's TypeCache at build time and invokes them after the core pipeline completes
// but before the final report/cleanup. Use ATOExtensionOrder to control ordering.
// 在你自己的程序集中实现 IATOPostProcessor；ATO 构建时通过 Unity 的 TypeCache 发现实现，
// 并在核心管线完成、最终报告/清理之前调用。用 ATOExtensionOrder 控制顺序。

using System;
using System.Collections.Generic;
using UnityEngine;

namespace net.fosa.ato
{
    /// <summary>
    /// Ordering attribute for post processors. Lower values run first. 后处理器的排序特性，数值越小越先执行。
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class ATOExtensionOrderAttribute : Attribute
    {
        public int Order { get; }
        public ATOExtensionOrderAttribute(int order) { Order = order; }
    }

    /// <summary>
    /// A generated texture record exposed to extensions. 暴露给扩展的生成贴图记录。
    /// </summary>
    public class ATOGeneratedTexture
    {
        /// <summary>The generated texture (atlas or rescaled texture). 生成的贴图（图集或缩放后的贴图）。</summary>
        public Texture2D texture;
        /// <summary>Human readable name. 可读名称。</summary>
        public string name;
        /// <summary>True if this is an atlas. 是否为图集。</summary>
        public bool isAtlas;
        /// <summary>Source textures merged into this atlas. 合并进该图集的来源贴图。</summary>
        public List<Texture2D> sources = new List<Texture2D>();
        /// <summary>Number of islands packed. 装箱的岛数量。</summary>
        public int islandCount;
        /// <summary>Utilization ratio 0..1. 利用率 0..1。</summary>
        public float utilization;
    }

    /// <summary>
    /// Context handed to post processors. 传递给后处理器的上下文。
    /// </summary>
    public class ATOPostProcessContext
    {
        /// <summary>Root of the avatar being processed. 被处理的 Avatar 根对象。</summary>
        public GameObject avatarRoot;
        /// <summary>Effective settings used for this build. 本次构建使用的有效设置。</summary>
        public ATOEffectiveSettings settings;
        /// <summary>Textures generated by the atlas / rescale stage. 图集/缩放阶段生成的贴图。</summary>
        public List<ATOGeneratedTexture> generatedTextures = new List<ATOGeneratedTexture>();
        /// <summary>Per-stage timing (stage name → ms). 各阶段耗时（阶段名 → 毫秒）。</summary>
        public Dictionary<string, double> stageTimings = new Dictionary<string, double>();
    }

    /// <summary>
    /// Post-processing hook. Runs after ATO's core pipeline, before the final report.
    /// 后处理钩子，在 ATO 核心管线之后、最终报告之前运行。
    /// </summary>
    public interface IATOPostProcessor
    {
        /// <summary>Display name used in logs. 日志中显示的名称。</summary>
        string DisplayName { get; }

        /// <summary>Invoked once per avatar build. 每次 Avatar 构建调用一次。</summary>
        void PostProcess(ATOPostProcessContext context);
    }
}
