// AvatarTextureOptimizer component.
// / AvatarTextureOptimizer 组件。
// This component is attached to the avatar root (the object carrying VRCAvatarDescriptor).
// It drives the whole NDMF build pipeline described in CLAUDE.md.
// / 该组件挂在 Avatar 根物体（带 VRCAvatarDescriptor 的对象）上，驱动 CLAUDE.md 描述的整条 NDMF 构建流水线。

using System;
using System.Collections.Generic;
using UnityEngine;
using VRC.SDK3.Avatars.Components;

namespace net.fosa.avatar_texture_optimizer.runtime
{
    /// <summary>UI language selection. / UI 语言选择。</summary>
    public enum AtoLanguage
    {
        Auto,             // follow NDMF / 跟随 NDMF
        English,          // en-US
        ChineseSimplified // zh-CN
    }

    /// <summary>
    /// Entry component of Avatar Texture Optimizer. Exactly one instance is allowed per avatar
    /// (including all children). The game object must have a VRCAvatarDescriptor.
    /// / ATO 的入口组件。每个 Avatar（含所有子物体）只允许挂载一个；挂载对象上必须存在 VRCAvatarDescriptor。
    /// </summary>
    [DisallowMultipleComponent]
    [AddComponentMenu("Avatar Texture Optimizer")]
    public sealed class AvatarTextureOptimizer : MonoBehaviour
    {
        // ===== Master switches / 总开关 =====
        [Tooltip("Generate atlases from UV islands. When off, no atlas is generated: no unused-UV culling, no UV repacking; textures are scaled as a whole and other optimizations still apply. / 生成图集。关闭时不会生成图集：不剔除未使用 UV、不重排 UV，直接缩放整张贴图并执行其他优化。")]
        public bool generateAtlas = true;

        [Tooltip("Also process additional mesh UV channels (UV1..UV7) as independent UV groups. When off, only UV0 is optimized. / 同时把网格的其他 UV 通道（UV1..UV7）作为独立 UV 组处理。关闭时只优化 UV0。")]
        public bool processAllUvChannels = false;

        [Tooltip("Deduplicate identical materials after optimization. / 优化后对内容与参数完全相同的材质去重。")]
        public bool deduplicateMaterials = true;

        [Tooltip("Deduplicate identical textures / atlases after optimization. / 优化后对内容与参数完全相同的贴图/图集去重。")]
        public bool deduplicateTextures = true;

        [Tooltip("Enable verbose [ATO] logs. / 开启详细的 [ATO] 日志。")]
        public bool verboseLogs = false;

        [Tooltip("UI language. Auto follows NDMF's current language. / UI 语言。自动跟随 NDMF 当前语言。")]
        public AtoLanguage language = AtoLanguage.Auto;

        [Tooltip("Max pixel size (long edge) of atlases / textures generated by ATO. 0 = auto (8192 desktop / 4096 mobile). / ATO 生成的图集/贴图长边最大像素。0 = 自动（桌面 8192 / 移动端 4096）。")]
        public int maxTextureSizeOverride = 0;

        // ===== Quality settings / 质量设置 =====
        public QualitySettings quality = new QualitySettings();

        // ===== Packing settings / 装箱设置 =====
        public PackingSettings packing = new PackingSettings();

        // ===== Output / 输出设置 =====
        public OutputSettings output = new OutputSettings();

        // ===== Platform overrides / 平台覆盖 =====
        public PlatformSettings platform = new PlatformSettings();

        // ===== Whitelist / 白名单 =====
        public List<WhitelistEntry> whitelist = new List<WhitelistEntry>();

        /// <summary>Whitelist entries: any object type (mesh, material, texture, animation...). / 白名单条目：任意对象类型（网格、材质、贴图、动画……）。</summary>
        [Serializable]
        public sealed class WhitelistEntry
        {
            [Tooltip("Any object referenced by an avatar: Mesh, Material, Texture, AnimationClip, GameObject, ... / Avatar 引用的任意对象：网格、材质、贴图、动画剪辑、GameObject……")]
            public UnityEngine.Object target;
            [Tooltip("Optional note. / 可选备注。")]
            public string note = "";
        }

        /// <summary>
        /// Quality presets backed by perceptual research. / 基于感知研究的质量挡位。
        /// Values are chosen from the literature (CIE ΔE2000 perceptibility, SSIM ~0.99 visually-lossless band, etc.).
        /// / 阈值取自文献（CIEDE2000 感知阈值、SSIM≈0.99 视觉无损区间等）。
        /// </summary>
        public enum QualityPreset
        {
            High,      // 高（默认）/ High (default)
            Medium,    // 中 / Medium
            Low,       // 低 / Low
            Custom,    // 自定义 / Custom
        }

        [Serializable]
        public sealed class QualityThresholds
        {
            [Tooltip("MS-SSIM lower bound (0~1). / MS-SSIM 下限（0~1）。")]
            public float ssim = 1f;
            [Tooltip("CIEDE2000 upper bound. / CIEDE2000 上限。")]
            public float deltaE = 0f;
            [Tooltip("Alpha channel metric upper bound: 1-IoU for Cutout, linear RMSE for Blend. / Alpha 指标上限：Cutout 用 1-IoU，Blend 用线性 RMSE。")]
            public float alpha = 0f;
            [Tooltip("Normal map angle error bound (degrees, p95). / 法线贴图角度误差上限（度，p95）。")]
            public float normalAngle = 0f;
            [Tooltip("Grayscale per-channel linear RMSE upper bound. / 灰度贴图逐通道线性 RMSE 上限。")]
            public float grayRms = 0f;
        }

        [Serializable]
        public sealed class QualitySettings
        {
            [Tooltip("Quality preset; changing it also changes the detailed thresholds. / 质量挡位；切换时详细阈值随之变化。")]
            public QualityPreset preset = QualityPreset.High;

            [Tooltip("Custom thresholds; only used when preset is Custom. They are never overwritten by other presets. / 自定义阈值；仅当挡位为自定义时生效，不会被其他挡位覆盖。")]
            public QualityThresholds custom = new QualityThresholds();

            // Pixel density clamps / 像素密度钳制
            [Tooltip("Pixel density presets (px per meter of avatar). / 像素密度挡位（avatar 每米的像素数）。")]
            public int[] densityOptions = { 512, 1024, 2048, 4096, 8192 };

            [Tooltip("Minimum pixel density (px/m). / 最小像素密度（px/m）。")]
            public int minPixelsPerMeter = 2048;

            [Tooltip("Maximum pixel density (px/m). / 最大像素密度（px/m）。")]
            public int maxPixelsPerMeter = 4096;

            [Tooltip("Scale the whole texture (non-atlas path) with this quality too. / 非图集路径下整张贴图也按此质量缩放。")]
            public bool scaleWholeTextureWhenNoAtlas = true;
        }

        [Serializable]
        public sealed class PackingSettings
        {
            [Tooltip("Minimum atlas side (POT). / 图集最小边长（2 的幂）。")]
            public int minAtlasSize = 64;

            [Tooltip("Maximum atlas side. 0 = auto (8192 desktop / 4096 mobile). / 图集最大边长。0 = 自动（桌面 8192 / 移动端 4096）。")]
            public int maxAtlasSize = 0;

            [Tooltip("Experimental: allow non-POT atlas sizes (64px steps). Requires formats that support NPOT with MipStreaming/Crunch (e.g. excludes PVRTC on iOS). / 实验性：允许非 2 的幂图集边长（64 步进）。需要支持 NPOT + MipStreaming/Crunch 的格式（如 iOS 排除 PVRTC）。")]
            public bool allowNPOT = false;

            [Tooltip("Minimum island padding (px). 4/8/16/32/64. / 最小岛间距（px）。4/8/16/32/64。")]
            public int minPadding = 4;

            [Tooltip("Enable GPU pull-push padding (bleed island edge colors into empty atlas areas). / 启用 GPU pull-push 外扩，把岛边缘颜色填充到图集空白区域。")]
            public bool pullPush = true;

            [Tooltip("Maximum islands per texture before falling back (safety). / 单张贴图超过该岛数时触发安全 fallback（保护）。")]
            public int maxIslandsPerTexture = 8192;
        }

        /// <summary>Per-category compression format. / 按贴图类别的压缩格式。</summary>
        public enum CompressionFormat
        {
            Auto,    // 自动（按平台/内容的最优解）/ Auto (best for platform & content)
            BC1,     // DXT1 (no alpha) / DXT1（无 alpha）
            BC7,     // High quality RGBA / 高质量 RGBA
            ETC2_RGB,
            ETC2_RGBA,
            ASTC_4x4,
            ASTC_6x6,
            ASTC_8x8,
            RGBA32,  // Uncompressed / 不压缩
            RGB24,   // Uncompressed RGB / 不压缩 RGB
            PVRTC_RGB4,
            PVRTC_RGBA4,
        }

        [Serializable]
        public sealed class CategorySettings
        {
            [Tooltip("Compression for opaque textures / atlases (no alpha). / 不透明贴图/图集（无 alpha）的压缩格式。")]
            public CompressionFormat opaque = CompressionFormat.Auto;
            [Tooltip("Compression for transparent textures / atlases (has alpha). / 透明贴图/图集（含 alpha）的压缩格式。")]
            public CompressionFormat transparent = CompressionFormat.Auto;
            [Tooltip("Compression for normal maps. / 法线贴图的压缩格式。")]
            public CompressionFormat normal = CompressionFormat.Auto;
            [Tooltip("Compression for grayscale/mask textures. / 灰度/蒙版贴图的压缩格式。")]
            public CompressionFormat grayscale = CompressionFormat.Auto;
        }

        [Serializable]
        public sealed class OutputSettings
        {
            [Tooltip("Enable Mipmap on generated atlases (binds MipStreaming on/off with it, as VRChat requires). / 生成的图集开启 Mipmap（与 MipStreaming 绑定，VRChat 要求）。")]
            public bool mipmap = true;

            [Tooltip("Read/Write is always disabled on generated atlases. / 生成的图集始终关闭 Read/Write（不可修改）。")]
            public bool readWrite = false;

            [Tooltip("Wrap mode is always Clamp on generated atlases. / 生成的图集始终为 Clamp。")]
            public bool forceClamp = true;

            public CategorySettings compression = new CategorySettings();
        }

        [Serializable]
        public sealed class PlatformSettings
        {
            [Tooltip("Enable per-platform overrides (like Unity platform override). / 启用各平台独立覆盖（类似 Unity 的 platform override）。")]
            public bool enableOverrides = false;

            [Tooltip("Build platform used as the base for platform-dependent defaults. / 作为平台相关默认值基准的构建平台。")]
            public BuildTargetHint defaultTarget = BuildTargetHint.Standalone;

            public PlatformOverride pc = new PlatformOverride();
            public PlatformOverride android = new PlatformOverride();
            public PlatformOverride ios = new PlatformOverride();
        }

        public enum BuildTargetHint
        {
            Standalone, // PC
            Android,
            iOS,
        }

        [Serializable]
        public sealed class PlatformOverride
        {
            [Tooltip("Override enabled for this platform. / 该平台启用覆盖。")]
            public bool enabled = false;

            [Tooltip("Max atlas side for this platform. / 该平台的最大图集边长。")]
            public int maxAtlasSize = 0;

            [Tooltip("Opaque compression for this platform. / 该平台的不透明压缩格式。")]
            public CompressionFormat opaque = CompressionFormat.Auto;
            [Tooltip("Transparent compression for this platform. / 该平台的透明压缩格式。")]
            public CompressionFormat transparent = CompressionFormat.Auto;
            [Tooltip("Normal map compression for this platform. / 该平台的法线压缩格式。")]
            public CompressionFormat normal = CompressionFormat.Auto;
            [Tooltip("Grayscale compression for this platform. / 该平台的灰度压缩格式。")]
            public CompressionFormat grayscale = CompressionFormat.Auto;
        }

        // ===== Helpers / 辅助 =====

        /// <summary>Validation used by the build. Throws with a clear message on invalid setups. / 构建时校验，非法配置直接报错。</summary>
        public void ValidateAvatarSetup()
        {
            if (GetComponent<VRCAvatarDescriptor>() == null)
            {
                throw new InvalidOperationException(
                    "[ATO] AvatarTextureOptimizer must be placed on the avatar root object which has a VRCAvatarDescriptor. / ATO 组件必须挂在带 VRCAvatarDescriptor 的 Avatar 根物体上。");
            }

            var all = GetComponentsInChildren<AvatarTextureOptimizer>(true);
            for (int i = 0; i < all.Length; i++)
            {
                if (all[i] != this)
                {
                    throw new InvalidOperationException(
                        "[ATO] Only one AvatarTextureOptimizer component is allowed per avatar (found on '" +
                        all[i].gameObject.name + "' too). / 每个 Avatar 只允许挂载一个 ATO 组件（'"
                        + all[i].gameObject.name + "' 上也发现了）。");
                }
            }
        }

        /// <summary>Effective max atlas size considering platform override. / 考虑平台覆盖后的有效最大图集边长。</summary>
        public int EffectiveMaxAtlasSize(BuildTargetHint hint, bool mobile)
        {
            if (platform.enableOverrides)
            {
                var o = hint == BuildTargetHint.Android ? platform.android
                    : hint == BuildTargetHint.iOS ? platform.ios
                    : platform.pc;
                if (o.enabled && o.maxAtlasSize > 0) return o.maxAtlasSize;
            }
            if (maxTextureSizeOverride > 0) return maxTextureSizeOverride;
            return mobile ? 4096 : 8192;
        }
    }
}
