// ATO — Avatar Texture Optimizer
// Applies the user's import-parameter choices (Mipmap + MipStreaming, compression tier,
// sRGB / alpha source) to non-whitelisted textures that were NOT regenerated by the atlas /
// whole-texture-scale stages. To never mutate shared source assets, a texture is cloned
// (re-encoded) only when its current import settings differ from the requested ones.
// 对未被图集 / 整图缩放阶段重新生成的非白名单贴图应用用户的导入参数选择（Mipmap + MipStreaming、
// 压缩挡位、sRGB / alpha 来源）。为绝不改动共享源资产，仅当当前导入设置与目标不一致时才克隆（重新编码）。

using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;
using net.fosa.ato;

namespace net.fosa.ato.editor
{
    /// <summary>
    /// Import settings for kept (non-regenerated) textures. 保留（未重新生成）贴图的导入设置。
    /// </summary>
    public static class OriginalTextureSettingsApplier
    {
        /// <summary>
        /// Apply settings to every kept, non-whitelisted texture and remap its usages.
        /// Returns the number of textures cloned.
        /// 对每张保留且非白名单的贴图应用设置并重映射用途，返回克隆的贴图数。
        /// </summary>
        public static int Apply(ATOBuildContext bc, ATOAnalysisResult result)
        {
            int cloned = 0;
            var remap = new Dictionary<Texture2D, Texture2D>();

            foreach (var texRef in result.textures)
            {
                bc.ThrowIfCancelled();
                if (texRef.whitelisted || texRef.texture == null) continue;
                if (HasReplacement(texRef)) continue; // atlas / scaled already handled 图集/缩放已处理

                var tex = texRef.texture;
                var importer = ATOTextureIO.GetImporter(tex);
                if (importer == null) continue; // embedded / procedural → leave untouched 内嵌/程序化贴图保持不动

                bool needClone = NeedsChange(importer, result.settings, out bool alpha);
                if (!needClone) continue;

                var copy = CloneAndConfigure(bc, tex, importer, result.settings, alpha);
                if (copy != null)
                {
                    remap[tex] = copy;
                    cloned++;
                    ATOLog.Verbose($"[Settings] cloned '{tex.name}' to apply import parameters.");
                }
            }

            if (remap.Count == 0) return cloned;

            // Update usages + animation references. 更新用途与动画引用。
            foreach (var texRef in result.textures)
            {
                if (texRef.texture != null && remap.TryGetValue(texRef.texture, out var copy))
                    texRef.texture = copy;
            }
            foreach (var usage in result.allUsages)
            {
                if (usage.texture != null && remap.TryGetValue(usage.texture, out var copy))
                    usage.texture = copy;
            }
            RemapAnimations(bc, result, remap);

            return cloned;
        }

        private static bool HasReplacement(ATOTextureRef texRef)
        {
            foreach (var u in texRef.usages)
                if (u.replacement != null) return true;
            return false;
        }

        private static bool NeedsChange(TextureImporter importer, ATOEffectiveSettings settings, out bool alpha)
        {
            alpha = importer.alphaSource != TextureImporterAlphaSource.None;
            // Single switch governs mipmap ⇔ streaming (VRChat requirement).
            // 单一开关同时控制 mipmap ⇔ streaming（VRChat 要求）。
            if (importer.mipmapEnabled != settings.mipmapsEnabled) return true;
            if (importer.streamingMipmaps != settings.mipmapsEnabled) return true;
            // Compression: "Auto" means leave as-is; explicit tiers change it.
            // 压缩：Auto 表示保持不变；显式挡位才修改。
            return false;
        }

        private static Texture2D CloneAndConfigure(ATOBuildContext bc, Texture2D src, TextureImporter orig, ATOEffectiveSettings settings, bool alpha)
        {
            if (!ATOTextureIO.TryReadPixels(src, out var rgba)) return null;

            var tmp = new Texture2D(src.width, src.height, TextureFormat.RGBA32, false, false);
            tmp.SetPixels32(rgba);
            tmp.Apply(false, false);

            var folder = string.IsNullOrEmpty(bc.AssetFolder) ? "Assets/ATO_Generated" : bc.AssetFolder;
            string path = AssetDatabase.GenerateUniqueAssetPath($"{folder}/ATO_{Sanitize(src.name)}.png");
            byte[] png = tmp.EncodeToPNG();
            Directory.CreateDirectory(Path.GetDirectoryName(path) ?? "Assets");
            File.WriteAllBytes(path, png);
            AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceSynchronousImport);
            UnityEngine.Object.DestroyImmediate(tmp);

            var importer = AssetImporter.GetAtPath(path) as TextureImporter;
            if (importer == null) return AssetDatabase.LoadAssetAtPath<Texture2D>(path);

            importer.textureType = orig.textureType;
            importer.sRGBTexture = orig.sRGBTexture;
            importer.mipmapEnabled = settings.mipmapsEnabled;
            importer.streamingMipmaps = settings.mipmapsEnabled;
            importer.isReadable = false;
            importer.wrapMode = orig.wrapMode;
            importer.filterMode = orig.filterMode;
            importer.anisoLevel = orig.anisoLevel;
            importer.alphaIsTransparency = orig.alphaIsTransparency;
            importer.alphaSource = orig.alphaSource;
            importer.textureCompression = orig.textureCompression; // keep original compression 保持原压缩
            importer.SaveAndReimport();

            var imported = AssetDatabase.LoadAssetAtPath<Texture2D>(path);
            if (imported != null) imported.name = "ATO_" + src.name;
            return imported;
        }

        private static void RemapAnimations(ATOBuildContext bc, ATOAnalysisResult result, Dictionary<Texture2D, Texture2D> remap)
        {
            var clips = new List<AnimationClip>();
            var seen = new HashSet<AnimationClip>();
            if (result.component != null)
            {
                var root = result.component.gameObject;
#if ATO_VRCSDK3
                var descriptor = root.GetComponent<VRC.SDK3.Avatars.Components.VRCAvatarDescriptor>();
                if (descriptor != null)
                {
                    foreach (var l in descriptor.baseAnimationLayers) Collect(l.animatorController, clips, seen);
                    foreach (var l in descriptor.specialAnimationLayers) Collect(l.animatorController, clips, seen);
                }
#endif
                foreach (var animator in root.GetComponentsInChildren<Animator>(true))
                    Collect(animator.runtimeAnimatorController, clips, seen);
            }
            foreach (var clip in clips)
            {
                if (clip == null) continue;
                bool changed = false;
                foreach (var binding in AnimationUtility.GetObjectReferenceCurveBindings(clip))
                {
                    var curve = AnimationUtility.GetObjectReferenceCurve(clip, binding);
                    if (curve == null) continue;
                    bool c2 = false;
                    for (int i = 0; i < curve.Length; i++)
                    {
                        if (curve[i].value is Texture2D t && remap.TryGetValue(t, out var rep)) { curve[i].value = rep; c2 = true; }
                    }
                    if (c2)
                    {
                        AnimationUtility.SetObjectReferenceCurve(clip, binding, curve);
                        changed = true;
                    }
                }
                if (changed) EditorUtility.SetDirty(clip);
            }
        }

        private static void Collect(RuntimeAnimatorController c, List<AnimationClip> clips, HashSet<AnimationClip> seen)
        {
            if (c == null) return;
            foreach (var clip in c.animationClips)
                if (clip != null && seen.Add(clip)) clips.Add(clip);
        }

        private static string Sanitize(string s)
        {
            foreach (var c in Path.GetInvalidFileNameChars()) s = s.Replace(c, '_');
            return s;
        }
    }
}
